【お試し】lighthouse-ci.yml調整

diff --git a/.github/workflows/lighthouse-ci.yml b/.github/workflows/lighthouse-ci.yml
--- a/.github/workflows/lighthouse-ci.yml
+++ b/.github/workflows/lighthouse-ci.yml
@@ -10,11 +10,11 @@ jobs:
         uses: actions/setup-node@v1
         with:
           node-version: 10.x
-      # - name: npm install, build
-      #   run: |
-      #     npm install
-      #     npm run build
+      - name: npm install, build
+        run: |
+          npm install
+          npm run build
       - name: run Lighthouse CI
         run: |
           npm install -g @lhci/cli@0.4.x
-          lhci autorun --upload.target=temporary-public-storage --staticDistDir=/src/.vuepress/dist || echo "LHCI failed!"
+          lhci autorun --upload.target=temporary-public-storage --collect.staticDistDir=/src/.vuepress/dist || echo "LHCI failed!"
